---
- name: Create ipv4 customs chains
  ansible.builtin.shell:
    cmd: "iptables -t {{ item.table }} -N {{ item.chain }}"
  loop: "{{ iptables_customs_chains | flatten }}"
  # loop_control:
  #   loop_var: customs_chains
  when:
    - item.state == "present"
    - item.ip_version == "ipv4"

- name: Remove ipv4 customs chains
  ansible.builtin.shell:
    cmd: "iptables -t {{ item.table }} -X {{ item.chain }}"
  loop: "{{ iptables_customs_chains | flatten }}"
  # loop_control:
  #   loop_var: customs_chains
  when:
    - item.state == "absent"
    - item.ip_version == "ipv4"

- name: Create ipv6 customs chains
  ansible.builtin.shell:
    cmd: "ip6tables -t {{ item.table }} -N {{ item.chain }}"
  loop: "{{ iptables_customs_chains | flatten }}"
  # loop_control:
  #   loop_var: customs_chains
  when:
    - item.state == "present"
    - item.ip_version == "ipv6"

- name: Remove ipv6 customs chains
  ansible.builtin.shell:
    cmd: "ip6tables -t {{ item.table }} -X {{ item.chain }}"
  loop: "{{ iptables_customs_chains | flatten }}"
  # loop_control:
  #   loop_var: customs_chains
  when:
    - item.state == "absent"
    - item.ip_version == "ipv6"
