---
- name: Add log for dropped traffic rules
  ansible.builtin.iptables:
    chain: "{{ logged_dropped.chain }}"
    table: "{{ logged_dropped.table }}"
    state: "{{ logged_dropped.state }}"
    ip_version: "{{ logged_dropped.ip_version }}"
    log_level: "{{ logged_dropped.log_level }}"
    log_prefix: "{{ logged_dropped.log_prefix }}"
    comment: log_traffic
  loop: "{{ iptables_add_log_for_dropped_traffic_list | flatten }}"
  loop_control:
    loop_var: logged_dropped
