---
- name: Add loopback rulesc
  ansible.builtin.iptables:
    chain: "{{ rules_loopback.chain }}"
    table: "{{ rules_loopback.table }}"
    state: "{{ rules_loopback.state }}"
    ip_version: "{{ rules_loopback.ip_version }}"
    in_interface: "{{ rules_loopback.in_interface | default(omit) }}"
    out_interface: "{{ rules_loopback.out_interface | default(omit) }}"
    jump: "{{ rules_loopback.jump }}"
    ctstate: NEW,ESTABLISHED,RELATED
    comment: allow_loopback_traffic
  loop: "{{ iptables_add_loopback_rules_list | flatten }}"
  loop_control:
    loop_var: rules_loopback
