---
- name: Manage packages
  become: true
  ansible.builtin.package:
    state: "{{ pkg.state }}"
    name: "{{ pkg.name }}"
  loop: "{{ iptables_pkgs | flatten }}"
  loop_control:
    loop_var: pkg

- name: Create empty default saved ipv4 rules file
  become: true
  ansible.builtin.file:
    path: "{{ iptables_conf_v4 }}"
    state: touch
    mode: "0600"
    owner: root
    group: root

- name: Create empty default saved ipv6 rules file
  become: true
  ansible.builtin.file:
    path: "{{ iptables_conf_v6 }}"
    state: touch
    mode: "0600"
    owner: root
    group: root

- name: Manage services
  become: true
  ansible.builtin.service:
    name: "{{ service.name }}"
    state: "{{ service.state }}"
    enabled: "{{ service.enabled }}"
    # daemon_reload: true
  loop: "{{ iptables_services | flatten }}"
  loop_control:
    loop_var: service
  ignore_errors: true
