---
- name: Set chains policy
  become: true
  ansible.builtin.iptables:
    chain: "{{ policy.chain }}"
    table: "{{ policy.table }}"
    state: "{{ policy.state }}"
    ip_version: "{{ policy.ip_version }}"
    policy: "{{ policy.policy }}"
  loop: "{{ iptables_policies | flatten }}"
  loop_control:
    loop_var: policy
    label: "ip: {{ policy.ip_version }}, table: {{ policy.table }}, chain: {{ policy.chain }}, policy: {{ policy.policy }}"
