---
- name: Reset policy
  ansible.builtin.iptables:
    chain: "{{ chains_policy.chain }}"
    table: "{{ chains_policy.table }}"
    state: "{{ chains_policy.state }}"
    ip_version: "{{ chains_policy.ip_version }}"
    policy: "{{ chains_policy.policy }}"
  loop: "{{ iptables_reset_default_policy_list | flatten }}"
  loop_control:
    loop_var: chains_policy
  when: iptables_reset_default_policy_list is iterable

- name: Flush ipv4 rules
  ansible.builtin.shell:
    cmd: "{{ iptables_binary_ipv4 }} -F"

- name: Flush ipv6 rules
  ansible.builtin.shell:
    cmd: "{{ iptables_binary_ipv6 }} -F"

- name: Reset ipv4 customs chains
  ansible.builtin.shell:
    cmd: "{{ iptables_binary_ipv4 }} -X"

- name: Reset ipv6 customs chains
  ansible.builtin.shell:
    cmd: "{{ iptables_binary_ipv6 }} -X"

- name: Purge ipv4 persistent file
  ansible.builtin.copy:
    content: ""
    dest: "{{ iptables_conf_v4 }}"
    owner: root
    group: root
    mode: "0644"
  ignore_errors: true

- name: Purge ipv6 persistent file
  ansible.builtin.copy:
    content: ""
    dest: "{{ iptables_conf_v6 }}"
    owner: root
    group: root
    mode: "0644"
  ignore_errors: true
