---
- name: reset chains policy
  ansible.builtin.iptables:
    chain: "{{ chains_policy.chain }}"
    table: "{{ chains_policy.table }}"
    state: "{{ chains_policy.state }}"
    ip_version: "{{ chains_policy.ip_version }}"
    policy: "{{ chains_policy.policy }}"
  loop: "{{ iptables_reset_chain_policy_list | flatten }}"
  loop_control:
    loop_var: chains_policy
  when: iptables_reset_chain_policy_list is iterable

- name: reset chains rules
  ansible.builtin.iptables:
    chain: "{{ chains_policy.chain }}"
    table: "{{ chains_policy.table }}"
    state: "{{ chains_policy.state }}"
    ip_version: "{{ chains_policy.ip_version }}"
    flush: true
  loop: "{{ iptables_reset_chain_policy_list | flatten }}"
  loop_control:
    loop_var: chains_policy
  when: iptables_reset_chain_policy_list is iterable

- name: reset ipv4 customs chains
  ansible.builtin.shell: "{{ iptables_binary_ipv4 }} -X"
  when: iptables_reset_chain_policy_customs_action | bool

- name: reset ipv6 customs chains
  ansible.builtin.shell: "{{ iptables_binary_ipv6 }} -X"
  when: iptables_reset_chain_policy_customs_action | bool

- name: reset ipv4 persistent file
  ansible.builtin.copy:
    content: ""
    dest: "{{ iptables_conf_v4 }}"
    owner: root
    group: root
    mode: "0644"
  ignore_errors: true

- name: reset ipv6 persistent file
  ansible.builtin.copy:
    content: ""
    dest: "{{ iptables_conf_v6 }}"
    owner: root
    group: root
    mode: "0644"
  ignore_errors: true
