---
- name: Set rules
  ansible.builtin.iptables:
    chain: "{{ rule.chain }}"
    table: "{{ rule.table }}"
    state: "{{ rule.state | default('present') }}"
    chain_management: "{{ rule.chain_management | default(true) }}"
    ip_version: "{{ rule.ip_version | default('ipv4') }}"
    comment: "{{ rule.comment | default(omit) }}"
    in_interface: "{{ rule.in_interface | default(omit) }}"
    source: "{{ rule.source | default(omit) }}"
    src_range: "{{ rule.src_range | default(omit) }}"
    source_port: "{{ rule.source_port | default(omit) }}"
    out_interface: "{{ rule.out_interface | default(omit) }}"
    destination: "{{ rule.destination | default(omit) }}"
    dst_range: "{{ rule.dst_range | default(omit) }}"
    destination_port: "{{ rule.destination_port | default(omit) }}"
    destination_ports: "{{ rule.destination_ports | default(omit) }}"
    protocol: "{{ rule.protocol | default('all') }}"
    icmp_type: "{{ rule.icmp_type | default(omit) }}"
    jump: "{{ rule.jump | default(omit) }}"
    goto: "{{ rule.goto | default(omit) }}"
    ctstate: "{{ rule.ctstate | default(omit) }}"
    gateway: "{{ rule.gateway | default(omit) }}"
    limit: "{{ rule.limit | default(omit) }}"
    limit_burst: "{{ rule.limit_burst | default(omit) }}"
    log: "{{ rule.log | default(omit) }}"
    log_level: "{{ rule.log_level | default(omit) }}"
    log_prefix: "{{ rule.log_prefix | default(omit) }}"
    match: "{{ rule.match | default(omit) }}"
    match_set: "{{ rule.match_set | default(omit) }}"
    match_set_flags: "{{ rule.match_set_flags | default(omit) }}"
    uid_owner: "{{ rule.uid_owner | default(omit) }}"
    gid_owner: "{{ rule.gid_owner | default(omit) }}"
    syn: "{{ rule.syn | default(omit) }}"
    tcp_flags: "{{ rule.tcp_flags | default(omit) }}"
    to_destination: "{{ rule.to_destination | default(omit) }}"
    to_ports: "{{ rule.to_ports | default(omit) }}"
    to_source: "{{ rule.to_source | default(omit) }}"
    wait: "{{ rule.wait | default(omit) }}"
  loop: "{{ iptables_rules | flatten }}"
  loop_control:
    loop_var: rule
