---
- name: configure rules traffic
  ansible.builtin.iptables:
    chain: "{{ iptables_rules.chain }}"
    table: "{{ iptables_rules.table }}"
    state: "{{ iptables_rules.state | default ('present') }}"
    ip_version: "{{ iptables_rules.ip_version | default ('ipv4') }}"
    comment: "{{ iptables_rules.comment | default (omit) }}"
    in_interface: "{{ iptables_rules.in_interface | default (omit) }}"
    source: "{{ iptables_rules.source | default (omit) }}"
    src_range: "{{ iptables_rules.src_range | default (omit) }}"
    source_port: "{{ iptables_rules.source_port | default (omit) }}"
    out_interface: "{{ iptables_rules.out_interface | default (omit) }}"
    destination: "{{ iptables_rules.destination | default (omit) }}"
    dst_range: "{{ iptables_rules.dst_range | default (omit) }}"
    destination_port: "{{ iptables_rules.destination_port | default (omit) }}"
    destination_ports: "{{ iptables_rules.destination_ports | default (omit) }}"
    protocol: "{{ iptables_rules.protocol | default ('all') }}"
    icmp_type: "{{ iptables_rules.icmp_type | default (omit) }}"
    jump: "{{ iptables_rules.jump | default (omit) }}"
    goto: "{{ iptables_rules.goto | default (omit) }}"
    ctstate: "{{ iptables_rules.ctstate | default (omit) }}"
    gateway: "{{ iptables_rules.gateway | default (omit) }}"
    limit: "{{ iptables_rules.limit | default (omit) }}"
    limit_burst: "{{ iptables_rules.limit_burst | default (omit) }}"
    log: "{{ iptables_rules.log | default (omit) }}"
    log_level: "{{ iptables_rules.log_level | default (omit) }}"
    log_prefix: "{{ iptables_rules.log_prefix | default (omit) }}"
    match: "{{ iptables_rules.match | default (omit) }}"
    match_set: "{{ iptables_rules.match_set | default (omit) }}"
    match_set_flags: "{{ iptables_rules.match_set_flags | default (omit) }}"
    uid_owner: "{{ iptables_rules.uid_owner | default (omit) }}"
    gid_owner: "{{ iptables_rules.gid_owner | default (omit) }}"
    syn: "{{ iptables_rules.syn | default (omit) }}"
    tcp_flags: "{{ iptables_rules.tcp_flags | default (omit) }}"
    to_destination: "{{ iptables_rules.to_destination | default (omit) }}"
    to_ports: "{{ iptables_rules.to_ports | default (omit) }}"
    to_source: "{{ iptables_rules.to_source | default (omit) }}"
  loop: "{{ iptables_customs_rules | flatten }}"
  loop_control:
    loop_var: iptables_rules
