---
- name: generate ipv4 persistent file
  ansible.builtin.shell:
    cmd: "{{ iptables_save_binary_ipv4 }} --file {{ iptables_conf_v4 }}"
  when: iptables_save_conf_action | bool

- name: generate ipv6 persistent file
  ansible.builtin.shell:
    cmd: "{{ iptables_save_binary_ipv6 }} --file {{ iptables_conf_v6 }}"
  when: iptables_save_conf_action | bool

- name: remove unwanted patterns in ipv4 persistent file
  ansible.builtin.lineinfile:
    path: "{{ iptables_conf_v4 }}"
    regexp: "{{ item }}"
    state: absent
  with_items: "{{ iptables_save_conf_remove_pattern_list }}"
  when: iptables_save_conf_remove_pattern | bool
    and
    iptables_save_conf_remove_pattern_list is defined
    and
    iptables_save_conf_remove_pattern_list is iterable

- name: remove unwanted patterns in ipv6 persistent file
  ansible.builtin.lineinfile:
    path: "{{ iptables_conf_v6 }}"
    regexp: "{{ item }}"
    state: absent
  with_items: "{{ iptables_save_conf_remove_pattern_list }}"
  when: iptables_save_conf_remove_pattern | bool
    and
    iptables_save_conf_remove_pattern_list is defined
    and
    iptables_save_conf_remove_pattern_list is iterable
